# numpyを使った行列演算

pythonを使って行列の演算を行う
numpyを使うと行列の積や逆行列、行列式、固有値などを簡単に算出できる。

numpyには汎用的な多次元配列のクラスnumpy.ndarrayと、行列(2次元配列)に特化したクラスnumpy.matrixがある。今回はndarrayを使うことにする。

今回することをまとめておくと  
・行列オブジェクトの生成: numpy.array(), numpy.reshape()  
・行列の要素の取得と変更  
・転置行列: .T属性  
・行列の和と差: +演算子, -演算子  
・スカラー倍と要素ごとの積: \*演算子, numpy.multiply()  
・行列の積: numpy.dot(), numpy.matmul(), @演算子  
・べき乗: \*\*演算子  
・ベクトルの内積: numpy.inner()  
・逆行列: numpy.linalg.inv()  
・行列式: numpy.linalg.det()  
・固有値と固有ベクトル: numpy.linalg.eig()  
・行列の結合･分割:   numpy.concatenate(axis), numpy.split(axis)  
・テンソル積: numpy.tensordot()  
・クロネッカー積: numpy.kron()

### 行列オブジェクトの生成  
numpy配列numpy.ndarrayはnumpy.array()で生成できる。  
第一引数にpythonのリストなどを渡す。

In [29]:
import numpy as np
arr=np.array([[0,1,2], [3,4,5]])
print(arr)
print(type(arr))

[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>


numpy.array()のほかには等差数列を生成する関数np.arange()などでもndarrayを生成できる。さらにreshape()メソッドで形状を変更したりすることも可能。

In [30]:
arr=np.arange(6)
print(arr)

arr=np.arange(6).reshape((2,3))
print(arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


そのほか、任意の形状を同じ値で初期化するnumpy.zeros(), numpy.ones(), numpy.full(), numpy.eye()などもある。

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 行列の要素の取得と変更(代入)  
pythonリスト型と同様に、numpy.ndarrayはarr[行番号][列番号]またはarr[行番号,列番号]でアクセスできる。行番号・式番号は0始まり。値を取得することも変更(代入)することもできる。

In [32]:
print(arr[0][1])
print(arr[0,1])
arr[0,1]=100
print(arr)

1
1
[[  0 100   2]
 [  3   4   5]]


### 転置行列: .T属性  
numpy.ndarrayは.Tで転置行列を取得できる。

In [33]:
arr=np.arange(6).reshape((2,3))
print(arr)

arr_t=arr.T
print(arr_t)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


### 行列の輪と積: +演算子, -演算子  
numpy.ndarrayでは、+演算子と-演算子でそれぞれ加算・減算できる。

In [34]:
arr1=np.arange(6).reshape((2,3))
print(arr1)

arr2=np.arange(0,12,2).reshape((2,3))
print(arr2)

arr_sum=arr1+arr2
print(arr_sum)

arr_sub=arr1-arr2
print(arr_sub)

[[0 1 2]
 [3 4 5]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  3  6]
 [ 9 12 15]]
[[ 0 -1 -2]
 [-3 -4 -5]]


### スカラー倍と要素ごとの積: \*演算子, numpy.multiply()  
numpy.ndarrayでは数値との\*演算は各要素のスカラー倍となる。

In [35]:
arr_mul=arr1*2
print(arr_mul)

[[ 0  2  4]
 [ 6  8 10]]


行列同士の要素ごとの積(アダマール積)を取得するには、numpy.multiply()を使う。

In [36]:
arr_mul=np.multiply(arr1,arr2)
print(arr_mul)

[[ 0  2  8]
 [18 32 50]]


numpy.ndarrayでは\*演算子はnumpy.multiply()と等価で、要素ごとの積算になる。

In [37]:
arr_mul=arr1*arr2
print(arr_mul)

[[ 0  2  8]
 [18 32 50]]


### 行列同士の積: numpy.dot(), numpy.matmul(), @演算子  
行列の積を算出するには、numpy.dot(), numpy.matmul(), @演算子を使う。

In [38]:
arr1=np.arange(4).reshape((2, 2))
print(arr1)
arr2=np.arange(6).reshape((2, 3))
print(arr2)

arr_mul_matrix=np.dot(arr1, arr2)
print(arr_mul_matrix)

arr_mul_matrix=arr1.dot(arr2)
print(arr_mul_matrix)

arr_mul_matrix=np.matmul(arr1,arr2)
print(arr_mul_matrix)

arr_mul_matrix=arr1@arr2
print(arr_mul_matrix)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 4 5]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]
[[ 3  4  5]
 [ 9 14 19]]


### べき乗:\*\*演算子  
\*\*演算子についてnumpy.ndarrayでは各要素に対してべき乗処理が行われる。

In [39]:
arr=np.arange(1,5).reshape(2,2)
print(arr)

arr_p=arr**2
print(arr_p)

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]


### ベクトルの内積: numpy.inner()  
行列(二次元配列)というテーマからずれるが、ベクトル(一次元配列)の内積を算出するにはnumpy.inner()を使う。

In [40]:
v1=np.array([0,1,2])
v2=np.array([3,4,5])
inner=np.inner(v1,v2)
print(inner)

14


numpy.dot(), numpy.matmul()でも引数が一次元配列の場合は内積を返すようになっている。@演算子でも同様。

### 逆行列: numpy.linalg.inv(),  
逆行列を算出するには、numpy.linalg.inv()を使う。

In [41]:
arr=np.array([[2,5],[1,3]])

arr_inv=np.linalg.inv(arr)
print(arr_inv)

print(arr@arr_inv)

[[ 3. -5.]
 [-1.  2.]]
[[1. 0.]
 [0. 1.]]


### 行列式: numpy.linalg.det()  
行列式を算出するには、numpy.linalg.det()を使う。

In [42]:
arr=np.array([[0,1],[2,3]])
det=np.linalg.det(arr)
print(det)

-2.0


### 固有値と固有ベクトル: numpy.linalg.eig()  
固有値と固有ベクトルを算出するには、numpy.linalg.eig()を使う。

n次正方行列に対して、n個の固有値が要素となる一次元配列wと、各列が各々の固有値に対応する固有ベクトルとなる二次元配列vが返される。

i個目の固有値w[i]と、i列目の固有ベクトルv[:,i]が対応している。固有ベクトルは1に規格化した値。

In [43]:
arr=np.array([[0,1], [1,0]])
w, v=np.linalg.eig(arr)

print(w)
print(v)

print('value:',w[0])
print('vector:',v[:,0]/v[0,0])

[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
value: 1.0
vector: [1. 1.]


最大固有値を求めたい場合は、最大値のインデックスを返すnumpy.argmax()を使えば良い。

In [44]:
print(w[np.argmax(w)])
print(v[:,np.argmax(w)])

1.0
[0.70710678 0.70710678]


以下のような関数を定義すると、対応する固有値と固有ベクトルのペアのタプルのリストを取得できる。固有ベクトルは1で規格化された値だとよく分からないので、各列の0ではない最も絶対値が小さい値で割っている。

In [45]:
def get_eigenpairs(arr):
    w,v=np.linalg.eig(arr)
    eigenpairs=[]
    
    for i,val in enumerate(w):
        vec=v[:,i]/np.min(np.abs(v[:,i][v[:,i] !=0]))
        eigenpairs.append((val,vec))
    
    return eigenpairs

eigenpairs=get_eigenpairs(arr)

for val,vec in eigenpairs:
    print('value: {}, vector: {}'.format(val,vec))

value: 1.0, vector: [1. 1.]
value: -1.0, vector: [-1.  1.]


3×3の例。 

In [46]:
arr=np.array([[1,1,2], [0,2,-1], [0,0,3]])
eigenpairs=get_eigenpairs(arr)

for val,vec in eigenpairs:
    print('value: {}, vector: {}'.format(val,vec))

value: 1.0, vector: [1. 0. 0.]
value: 2.0, vector: [1. 1. 0.]
value: 3.0, vector: [ 1. -2.  2.]


複素数も扱うことができる。虚数単位はjで表される。

In [47]:
arr=np.array([[3,2], [-2,3]])
eigenpairs=get_eigenpairs(arr)

for val,vec in eigenpairs:
    print('value: {}, vector: {}'.format(val,vec))

value: (3+2.0000000000000004j), vector: [0.-1.j 1.+0.j]
value: (3-2.0000000000000004j), vector: [0.+1.j 1.-0.j]


In [48]:
arr=np.array([[1,4,1,4], [2,1,3,5], [6,2,3,5], [3,2,2,2]])
arr_inv=np.linalg.inv(arr)
print(arr_inv*83)

[[ -4. -18.  24.  -7.]
 [ 16. -11. -13.  28.]
 [-21.  30. -40.  67.]
 [ 11.   8.  17. -43.]]


### 行列の結合･分割:   numpy.concatenate(axis), numpy.split(axis)  
下にくっつける様に行列同士の結合を行う際にはconcatenate(axis=0)を用いる。  
右にくっつける様に行列同士の結合を行う際にはconcatenate(axis=1)を用いる。  
この記法なら次元が上がっても対応できる。

In [49]:
arr1=np.arange(6).reshape(2,3)
arr2=np.arange(6,12).reshape(2,3)

arr_v=np.concatenate((arr1,arr2),axis=0)
print(arr_v)

arr_h=np.concatenate((arr1,arr2),axis=1)
print(arr_h)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


行列の分割を行う際にはnumpy.split(axis)を使う。  
上下に分割させるときはsplit(axis=0)を用いる。  
左右に分割させるときはsplit(axis=1)を用いる。

In [50]:
arr=np.arange(12).reshape(3,4)

a,b=np.split(arr,[1],axis=0)
print(a)
print(b)

a,b=np.split(arr,2,axis=1)
print(a)
print(b)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


### テンソル積: numpy.tensordot()  
テンソル積を算出するにはnumpy.tensordot()を使う。

In [51]:
arr1=np.array([[1,0],
               [0,1]])
arr2=np.array([[2,3],
               [4,5]])

arr_tensor=np.tensordot(arr1,arr2,0)
print(arr_tensor)

[[[[2 3]
   [4 5]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[2 3]
   [4 5]]]]


テンソル積をもっと扱いやすい形で算出したい。

In [52]:
def get_td(a,b):
    x=np.tensordot(a,b,0)
    return np.concatenate([np.concatenate(x[i],axis=1) for i in range(len(x))],axis=0)

In [53]:
get_td(arr1,arr2)

array([[2, 3, 0, 0],
       [4, 5, 0, 0],
       [0, 0, 2, 3],
       [0, 0, 4, 5]])

### クロネッカー積: numpy.kron()  
二次元の行列において上のテンソル積はクロネッカー積とよく似ている

In [54]:
np.kron(arr1,arr2)

array([[2, 3, 0, 0],
       [4, 5, 0, 0],
       [0, 0, 2, 3],
       [0, 0, 4, 5]])